# Configuração do site Jekyll para GitHub Pages
title: "ALB Sistemas"
description: "Soluções em Sistemas para sua Empresa"
baseurl: "/ALB-SITEs" # Nome do repositório GitHub
url: "https://larissatrombini.github.io" # URL base do GitHub Pages

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
